before_script:
  - export CONAN_USER_HOME=${PWD}
  - mkdir -p build
  - cd build
  - conan install --build=missing --settings compiler=${CONAN_COMPILER} --settings compiler.version=${CONAN_COMPILER_VERSION} --settings compiler.libcxx=${CONAN_COMPILER_LIBCXX} ..

cache:
  paths:
    - .conan

linux_x86_64_build:
  stage: build
  script:
    - cmake ..
    - make -j$(nproc)
  tags:
    - cxx14
    - x86_64
    - linux
    - clang36
    - libcxx
  artifacts:
    paths:
      - build/products/Release/bin/botanio
