before_script:
  - export CONAN_USER_HOME=${PWD}
  - mkdir -p build
  - cd build
  - pip install conan
  - conan install --build=missing ..

cache:
  paths:
    - .conan

linux_x86_64_build:
  stage: build
  script:
    - cmake ..
    - make -j$(nproc)
  tags:
    - cxx14
    - x86_64
    - linux
  artifacts:
    paths:
      - build/products/Release/bin/botanio
