before_script:
  - export CONAN_USER_HOME=${PWD}
  - mkdir -p build
  - cd build
  - pip install conan
  - conan install --build=missing ..

cache:
  paths:
    - .conan

x86_64:
  script:
    - cmake ..
    - make -j$(nproc)
  tags:
    - cxx14
    - x86_64
  artifacts:
    paths:
      - build/products/Release/bin/botanio

armv7:
  script:
    - cmake ..
    - make -j$(nproc)
  tags:
    - cxx14
    - armv7
  artifacts:
    paths:
      - build/products/Release/bin/botanio
