find_package(PkgConfig)

pkg_check_modules(BOTAN botan-1.11 QUIET)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Botan DEFAULT_MSG BOTAN_LIBRARIES BOTAN_LIBRARY_DIRS BOTAN_INCLUDE_DIRS)

mark_as_advanced(BOTAN_INCLUDE_DIRS BOTAN_LIBRARY_DIRS BOTAN_LIBRARIES)
